// <auto-generated />
using System;
using LojaLegos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaLegos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230711191957_roleSeeds")]
    partial class roleSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LojaLegos.Models.Armazem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ResponsavelFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelFK");

                    b.ToTable("Armazem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Local = "Tomar",
                            ResponsavelFK = 1
                        });
                });

            modelBuilder.Entity("LojaLegos.Models.Artigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArmazemFK")
                        .HasColumnType("int");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrPecas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Stock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ArmazemFK");

                    b.ToTable("Artigos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArmazemFK = 1,
                            Detalhes = "gosfdnaiudsf",
                            Foto = "42004.jpg",
                            Nome = "Mini blackhoe Loader",
                            Nr = "42004",
                            NrPecas = "97",
                            Preco = 113.99m,
                            Stock = "5",
                            Tipo = "Technic"
                        },
                        new
                        {
                            Id = 2,
                            ArmazemFK = 1,
                            Detalhes = "não voa",
                            Foto = "42057.jpg",
                            Nome = "Ultralight Helicopter",
                            Nr = "42057",
                            NrPecas = "105",
                            Preco = 119.99m,
                            Stock = "99",
                            Tipo = "Technic"
                        },
                        new
                        {
                            Id = 3,
                            ArmazemFK = 1,
                            Detalhes = "",
                            Foto = "60239.jpg",
                            Nome = "Police Car",
                            Nr = "60238",
                            NrPecas = "94",
                            Preco = 19.99m,
                            Stock = "36",
                            Tipo = "City"
                        },
                        new
                        {
                            Id = 4,
                            ArmazemFK = 1,
                            Detalhes = "",
                            Foto = "60292.jpg",
                            Nome = "Headquarters",
                            Nr = "60292",
                            NrPecas = "790",
                            Preco = 64.99m,
                            Stock = "47",
                            Tipo = "City"
                        },
                        new
                        {
                            Id = 5,
                            ArmazemFK = 1,
                            Detalhes = "",
                            Foto = "6157.jpg",
                            Nome = "Zoo",
                            Nr = "6157",
                            NrPecas = "101",
                            Preco = 49.99m,
                            Stock = "93",
                            Tipo = "Duplo"
                        },
                        new
                        {
                            Id = 6,
                            ArmazemFK = 1,
                            Detalhes = "",
                            Foto = "10959.jpg",
                            Nome = "Police Station",
                            Nr = "10959",
                            NrPecas = "40",
                            Preco = 49.99m,
                            Stock = "12",
                            Tipo = "Duplo"
                        },
                        new
                        {
                            Id = 7,
                            ArmazemFK = 1,
                            Detalhes = "",
                            Foto = "8831.jpg",
                            Nome = "Atlas",
                            Nr = "8831",
                            NrPecas = "1",
                            Preco = 9.99m,
                            Stock = "68",
                            Tipo = "Minifigures"
                        },
                        new
                        {
                            Id = 8,
                            ArmazemFK = 1,
                            Detalhes = "",
                            Foto = "71011.jpg",
                            Nome = "Field Worker",
                            Nr = "71011",
                            NrPecas = "1",
                            Preco = 9.99m,
                            Stock = "76",
                            Tipo = "Minifigures"
                        });
                });

            modelBuilder.Entity("LojaLegos.Models.ArtigoEncomenda", b =>
                {
                    b.Property<int>("ArtigoId")
                        .HasColumnType("int");

                    b.Property<int>("EncomendaId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("ArtigoId", "EncomendaId");

                    b.HasIndex("EncomendaId");

                    b.ToTable("ArtigoEncomendas");

                    b.HasData(
                        new
                        {
                            ArtigoId = 1,
                            EncomendaId = 1,
                            Quantidade = 23
                        },
                        new
                        {
                            ArtigoId = 2,
                            EncomendaId = 1,
                            Quantidade = 26
                        });
                });

            modelBuilder.Entity("LojaLegos.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CodPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrContribuinte")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("NrTelemovel")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("País")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apelido = "Mendes",
                            Cidade = "Santo António dos Cavaleiros",
                            CodPostal = "2660-284",
                            Email = "goncalomendes@sapo.pt",
                            Morada = "Rua...",
                            NrContribuinte = "412414141",
                            NrTelemovel = "941941941",
                            País = "Portugal",
                            PrimeiroNome = "Gonçalo",
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("LojaLegos.Models.Encomenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteFK");

                    b.ToTable("Encomendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteFK = 1,
                            Data = new DateTime(2023, 6, 25, 13, 58, 56, 0, DateTimeKind.Unspecified),
                            Estado = "expedido",
                            Total = "3000"
                        });
                });

            modelBuilder.Entity("LojaLegos.Models.Funcs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChefeFK")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrTelemovel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChefeFK");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cargo = "Funcionário",
                            ChefeFK = 1,
                            Email = "beatrizpatita@blabla.com",
                            Nome = "Beatriz",
                            NrTelemovel = "942942942",
                            UserId = "2"
                        });
                });

            modelBuilder.Entity("LojaLegos.Models.Gestor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrTelemovel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gestor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cargo = "Gestor",
                            Email = "luisfreitas@blabla.com",
                            Foto = "",
                            Nome = "Luís Freitas",
                            NrTelemovel = "943943943",
                            UserId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c",
                            ConcurrencyStamp = "4c657d71-af54-4aa9-bad7-7c59e9d56fbe",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        },
                        new
                        {
                            Id = "g",
                            ConcurrencyStamp = "dde4332a-c8e1-4485-acd7-0e81acf260ac",
                            Name = "Gestor",
                            NormalizedName = "GESTOR"
                        },
                        new
                        {
                            Id = "f",
                            ConcurrencyStamp = "2e87af43-f51c-44cd-b475-88860b0873dc",
                            Name = "Funcionario",
                            NormalizedName = "FUNCIONARIO"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3",
                            RoleId = "g"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "f"
                        },
                        new
                        {
                            UserId = "1",
                            RoleId = "c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LojaLegos.Data.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bd96693c-c916-4a11-a26a-2c704d1f0623",
                            Email = "cliente2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "CLIENTE2@GMAIL.COM",
                            NormalizedUserName = "CLIENTE2@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEyRx63lQ6mT2pVUsWDFmErzB22cKY4P+WYDasX8cNmEwWOJcHwRhgcU0Y1tCz2GMw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e11e5506-b95c-4975-8aa9-f3f0a478ab9d",
                            TwoFactorEnabled = false,
                            UserName = "cliente2@gmail.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "543b3402-bfe2-4b40-9464-6b5d7372ccda",
                            Email = "beatrizpatita@blabla.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "BEATRIZPATITA@BLABLA.COM",
                            NormalizedUserName = "BEATRIZPATITA@BLABLA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBgxOv+wVnE6ItddeZXlVI/eN1SQMA76HcFO6LA250zpGgoH0Oz8epQNJavRAm9HdA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c7326415-36cc-487c-adc4-95056afc06a5",
                            TwoFactorEnabled = false,
                            UserName = "beatrizpatita@blabla.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9ea3c5f3-4855-4fde-9ce8-e1b87e11d5db",
                            Email = "Luisfreitas@blabla.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "LUISFREITAS@BLABLA.COM",
                            NormalizedUserName = "LUISFREITAS@BLABLA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEK5F+W1m/i1rhfC5Lx+kNKZbeV4jEgDdD1OjEBHBnmywtXG7XTi5Pwfv/XCNL41Wdg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3ef63632-f763-4834-b2e5-8c52efc4e40f",
                            TwoFactorEnabled = false,
                            UserName = "Luisfreitas@blabla.com"
                        });
                });

            modelBuilder.Entity("LojaLegos.Models.Armazem", b =>
                {
                    b.HasOne("LojaLegos.Models.Funcs", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("LojaLegos.Models.Artigo", b =>
                {
                    b.HasOne("LojaLegos.Models.Armazem", "Armazem")
                        .WithMany("Artigos")
                        .HasForeignKey("ArmazemFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armazem");
                });

            modelBuilder.Entity("LojaLegos.Models.ArtigoEncomenda", b =>
                {
                    b.HasOne("LojaLegos.Models.Artigo", "Artigo")
                        .WithMany("ArtigoEncomendas")
                        .HasForeignKey("ArtigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LojaLegos.Models.Encomenda", "Encomenda")
                        .WithMany("ArtigoEncomendas")
                        .HasForeignKey("EncomendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");

                    b.Navigation("Encomenda");
                });

            modelBuilder.Entity("LojaLegos.Models.Encomenda", b =>
                {
                    b.HasOne("LojaLegos.Models.Cliente", "Cliente")
                        .WithMany("Encomendas")
                        .HasForeignKey("ClienteFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("LojaLegos.Models.Funcs", b =>
                {
                    b.HasOne("LojaLegos.Models.Gestor", "Gestor")
                        .WithMany("Funcionarios")
                        .HasForeignKey("ChefeFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gestor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LojaLegos.Models.Armazem", b =>
                {
                    b.Navigation("Artigos");
                });

            modelBuilder.Entity("LojaLegos.Models.Artigo", b =>
                {
                    b.Navigation("ArtigoEncomendas");
                });

            modelBuilder.Entity("LojaLegos.Models.Cliente", b =>
                {
                    b.Navigation("Encomendas");
                });

            modelBuilder.Entity("LojaLegos.Models.Encomenda", b =>
                {
                    b.Navigation("ArtigoEncomendas");
                });

            modelBuilder.Entity("LojaLegos.Models.Gestor", b =>
                {
                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
